# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Podcast Feed settings
title:          Set, Scene, Shot.
description:    "Curious about the meaning behind the burning of a boyfriend in Midsommar? Or the doppelganger dance in Annihilation? Join us for Set Scene Shot where we dissect scenes and themes from your favorite independent films. We’ll examine the cultural context, visual symbolism and subtle artistry which ground iconic cinema scenes. Airing Tuesdays, every other week!"
email:          gerg350z@gmail.com
subtitle:       "none"
url:            https://greglee1905.github.io/setsceneshot/
language:       en-us
author:         Vasiliki Karahalios & Greg Lee
copyright:      "CC BY 4.0"

feed:
  collections:
    episodes:
      path: "/episodes.xml"

collections:
  episodes:
